# Generated by Django 3.0.4 on 2020-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='language',
            field=models.CharField(choices=[(1, 'Credit Card'), (12, 'Student Loans'), (13, 'Taxes'), (21, 'Books'), (22, 'Games'), (31, 'Groceries'), (32, 'Restaurants')], default=1, max_length=1),
        ),
    ]
