# Generated by Django 3.0.4 on 2020-03-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_labpost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='language',
            field=models.CharField(choices=[('ZOK', 'Credit Card'), (12, 'Student Loans'), (13, 'Taxes'), (21, 'Books'), (22, 'Games'), (31, 'Groceries'), (32, 'Restaurants')], default='ZOK', max_length=3),
        ),
    ]
