# Generated by Django 3.0.4 on 2020-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_labpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, max_length=1),
        ),
    ]
