# Generated by Django 3.0.4 on 2020-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20200322_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='stream',
            field=models.CharField(default='cse', max_length=100),
        ),
        migrations.AddField(
            model_name='labpost',
            name='subject',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
