# Generated by Django 3.0.4 on 2020-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20200322_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='stream',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CV', 'CV'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('B-ARCH', 'B-ARCH'), ('BBA-HEM', 'BBA-HEM'), ('B-DES', 'B-DES')], default='CSE', max_length=30),
        ),
    ]
