# Generated by Django 3.0.4 on 2020-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20200323_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='labpost',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='labpost',
            name='postbody',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
