# Generated by Django 3.0.4 on 2020-03-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20200323_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
