# Generated by Django 3.0.4 on 2020-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20200323_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='postbody',
            field=models.TextField(),
        ),
    ]
