# Generated by Django 3.0.4 on 2020-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_filepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepost',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='filepost/'),
        ),
        migrations.AddField(
            model_name='filepost',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='filepost/'),
        ),
        migrations.AddField(
            model_name='filepost',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='filepost/'),
        ),
        migrations.AddField(
            model_name='filepost',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='filepost/'),
        ),
    ]
