# Generated by Django 3.0.4 on 2020-04-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_auto_20200429_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpost',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
    ]
