# Generated by Django 3.0.4 on 2020-04-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_auto_20200429_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpost',
            name='language',
        ),
    ]
