# Generated by Django 3.0.3 on 2020-03-09 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profle',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='immage',
            new_name='image',
        ),
    ]
